const rootPrefix = '../..',
  apiNameConstants = require(rootPrefix + '/lib/globalConstant/apiName');

const webRouteSpec = {
  'POST /api/connect': {
    apiName: apiNameConstants.authenticateUser,
    summary: 'Authenticate and signin user',
    tag: 'Authenticaion'
  },

  'POST /api/logout': {
    apiName: apiNameConstants.logout,
    summary: 'Logs out authenticated user',
    tag: 'Authenticaion'
  },

  'GET /api/current-user': {
    apiName: apiNameConstants.getCurrentUser,
    summary: 'Get authenticated user and details',
    tag: 'Authenticaion'
  },

  'POST /api/reaction': {
    apiName: apiNameConstants.addReactionToNFT,
    summary: 'Record reaction on nft and image',
    tag: 'Vote NFTs'
  },

  'GET /api/nfts': {
    apiName: apiNameConstants.getNftsToVoteApiName,
    summary: 'Get all nfts and images to vote for a user',
    tag: 'Vote NFTs'
  },

  'GET /api/image-suggestions': {
    apiName: apiNameConstants.getImageSuggestions,
    summary: 'Get image suggestions generated by stable diffusion',
    tag: 'Generate Flow'
  },

  'POST /api/store-on-ipfs': {
    apiName: apiNameConstants.storeOnIpfsApiName,
    summary: 'Store image and metadata on ipfs and database',
    tag: 'Generate Flow'
  },

  'POST /api/submit-to-vote': {
    apiName: apiNameConstants.submitToVote,
    summary: 'Record lens post and image',
    tag: 'Generate Flow'
  },

  'GET /api/collect-nfts': {
    apiName: apiNameConstants.getNftsToCollect,
    summary: 'Get all voted and collected nfts and images for a user',
    tag: 'Collect NFTs'
  },

  'GET /api/hall-of-flame-nfts': {
    apiName: apiNameConstants.getNftsForHallOfFlame,
    summary: 'Get all voted and collected nfts and images for a user',
    tag: 'Collect NFTs'
  },

  'POST /api/collect': {
    apiName: apiNameConstants.markCollected,
    summary: 'Mark lens post as collected nft',
    tag: 'Collect NFTs'
  }
};

module.exports = webRouteSpec;
