replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "nftornot-backend"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 3000

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: thursday
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health-checker
  hosts:
    - host: nftornot.com
      paths:
        - path: /api
          pathType: Prefix

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 1
    memory: 2Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

env:
  S3_BUCKET: "nftornot-assests"

envSecrets:
  STABILITY_KEY: "non"
  SIGNER_PK: "non"
  AWS_ACCESS_KEY_ID: sd-user
  AWS_SECRET_ACCESS_KEY: sd-user
  WEB3_STORAGE_IPFS_TOKEN: non2
  INFURA_PROJECT_ID: non2
  INFURA_API_SECRET_KEY: non2
